### ISSUE TITLE
Site Not Loading at "www.thebreadbook.org"

### ISSUE THREAD

**Issue by manicatorman** [breadbook/thebreadbook.org#2]
I wasn't sure if you were aware of this, but while the site is working fine at [https://thebreadbook.org](https://thebreadbook.org), it doesn't appear to be working when you add the "www" - [https://www.thebreadbook.org](https://www.thebreadbook.org). Let me know if there is something I need to do!

**Comment by nteiv** [comment]
working on it right now. had to reset the server for the time being due to a mistyped server block. will probably be down for a couple of hours.

dont know why I didn't get an email notification of this issue

**Comment by breadbook** [comment]
Fixed the mistyped server block in my Nginx config. DNS resolves fine now.

**Comment by manicatorman** [comment]
@breadbook Awesome! Glad that is fixed! :+1:
